import type { NextPage } from 'next';
import Head from 'next/head';
import MainDashboard from '../components/dashboard/main-dashboard';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Cardano Dapp</title>
        <meta name="description" content="Generated by create-cardano-dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainDashboard></MainDashboard>
    </>
  );
};

export default Home;
